name: Deploy Vite App to GitHub Pages

on:
    push:
        branches:
            - main # Cambia a "master" si esa es tu rama principal

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. Clonar el repositorio
            - name: Checkout code
              uses: actions/checkout@v2

            # 2. Configurar Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "lts/*"

            # 3. Instalar dependencias
            - name: Install dependencies
              run: npm install

            # 4. Construir el proyecto
            - name: Build project
              run: npm run build

            # 5. Desplegar en GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }} # Usa GITHUB_TOKEN para repositorios públicos
                  publish_dir: ./dist

            # 6. Opcional: Instalar navegadores para Playwright
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            # 7. Opcional: Ejecutar pruebas con Playwright
            - name: Run Playwright tests
              run: npx playwright test

            # 8. Opcional: Subir reporte de Playwright como artefacto
            - name: Upload Playwright report
              if: ${{ always() }}
              uses: actions/upload-artifact@v3
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
